download subtitles for every video, if they exist

diff --git a/googlegargle b/googlegargle
--- a/googlegargle
+++ b/googlegargle
@@ -3,8 +3,7 @@
 # GOOGLEGARGLE: Given a unique docid as an argument, do your worst.
 
 ARIA=$(which aria2c)
-#ARIAOPTIONS="--max-overall-download-limit=90M --file-allocation=none --min-split-size=1M --log-level=notice --remote-time=true"
-ARIAOPTIONS="--max-overall-download-limit=90M --file-allocation=none --log-level=notice --remote-time=true --max-file-not-found=1"
+ARIAOPTIONS="--max-overall-download-limit=90M --file-allocation=none --min-split-size=1M --log-level=notice --remote-time=true --max-file-not-found=1"
 DLSCRIPT=$(which youtube-dl)
 
 __exists () {
@@ -44,83 +43,88 @@ if [ ! -f "$DLSCRIPT" ]
 fi
 
 HOMEBASE=$(pwd)
+__exists wget && getCommand="wget" && getArgs="-O"
+__exists fetch && getCommand="fetch" && getArgs="-o"
 
 grab_by_id() {
-id=$1
-
-cd $HOMEBASE
-
-# Account for how people shove things at the script.
-
-EQUALS=$(echo $id | grep =)
-
-if [ $EQUALS ]
-   then
-   id=$(echo $id | cut -f2 -d"=")
-fi
-
-echo $id
-
-cd $HOMEBASE
-
-SEPDIB=$(echo "$id" | sed 's/-//g' | cut -c1)
-SECDIB=$(echo "$id" | sed 's/-//g' | cut -c2)
-THIRDIB=$(echo "$id" | sed 's/-//g' | cut -c3)
-
-echo "$SEPDIB - $SECDIB - $THIRDIB"
-
-if [ ! -d $SEPDIB ]
-   then
-   echo "First ID for $SEPDIB! Creating."
-   mkdir $SEPDIB
-   cd $SEPDIB
-   else
-   cd $SEPDIB
-fi
-
-if [ ! -d $SECDIB ]
-   then
-   echo "First ID for $SEPDIB/$SECDIB! Creating."
-   mkdir $SECDIB
-   cd $SECDIB
-   else
-   cd $SECDIB
-fi
-
-if [ ! -d $THIRDIB ]
-   then
-   echo "First ID for $SEPDIB/$SECDIB/$THIRDIB! Creating."
-   mkdir $THIRDIB
-   cd $THIRDIB
-   else
-   cd $THIRDIB
-fi
-
-if [ -f "$id/$id.flv" -a ! -f "$id/$id.flv.aria2" ]
-then
+  id=$1
+  
+  cd $HOMEBASE
+  
+  # Account for how people shove things at the script.
+  
+  EQUALS=$(echo $id | grep =)
+  
+  if [ $EQUALS ]
+     then
+     id=$(echo $id | cut -f2 -d"=")
+  fi
+  
+  echo $id
+  
+  cd $HOMEBASE
+  
+  SEPDIB=$(echo "$id" | sed 's/-//g' | cut -c1)
+  SECDIB=$(echo "$id" | sed 's/-//g' | cut -c2)
+  THIRDIB=$(echo "$id" | sed 's/-//g' | cut -c3)
+  
+  echo "$SEPDIB - $SECDIB - $THIRDIB"
+  
+  if [ ! -d $SEPDIB ]
+     then
+     echo "First ID for $SEPDIB! Creating."
+     mkdir $SEPDIB
+     cd $SEPDIB
+     else
+     cd $SEPDIB
+  fi
+  
+  if [ ! -d $SECDIB ]
+     then
+     echo "First ID for $SEPDIB/$SECDIB! Creating."
+     mkdir $SECDIB
+     cd $SECDIB
+     else
+     cd $SECDIB
+  fi
+  
+  if [ ! -d $THIRDIB ]
+     then
+     echo "First ID for $SEPDIB/$SECDIB/$THIRDIB! Creating."
+     mkdir $THIRDIB
+     cd $THIRDIB
+     else
+     cd $THIRDIB
+  fi
+  
+  if [ -f "$id/$id.flv" -a ! -f "$id/$id.flv.aria2" ]
+  then
     echo "There is already a $id downloaded. Hooray."
-else
+  else
     [ -d "$id" ] && echo "Resuming $id." || mkdir -- "$id"
     cd -- "$id"
-    __exists wget && getCommand="wget" && getArgs="-O"
-    __exists fetch && getCommand="fetch" && getArgs="-o"
     retry_time=2
     while true; do
-        (
-            $getCommand $getArgs "$id.html" "http://video.google.com/videoplay?docid=$id" || exit $?
-            grep -- "video-title>" "$id.html" | cut -f2 -d">" | cut -f1 -d"<"
-            $ARIA $ARIAOPTIONS -o $id.flv "$($DLSCRIPT -g http://video.google.com/videoplay?docid=$id)"  || exit $?
-        ) && break
-	if [ $retry_time -gt 32 ]; then
-	  echo "Too many errors on $id, giving up on this one."
-	  echo "$id" >> $HOMEBASE/failed.list
-	  break
-	fi
-        echo "Error while downloading. Will retry in $retry_time seconds."
-        sleep $retry_time
-        retry_time=$(( $retry_time * 2 ))
+      ($getCommand $getArgs "$id.html" "http://video.google.com/videoplay?docid=$id" || exit $?
+       grep -- "video-title>" "$id.html" | cut -f2 -d">" | cut -f1 -d"<"
+       $ARIA $ARIAOPTIONS -o $id.flv "$($DLSCRIPT -g http://video.google.com/videoplay?docid=$id)" || exit $?
+       $getCommand $getArgs "$id.xml" "http://video.google.com/videotranscript?docid=$id&type=list"
+       cat "$id.xml" | tr ">" "\n" | grep "$<track " | while read $line; do
+         tid=`echo $line | sed -n -e 's/.*id="\([^"]*\)".*/\1/p'`
+         name=`echo $line | sed -n -e 's/.*name="\([^"]*\)".*/\1/p'`
+         lang=`echo $line | sed -n -e 's/.*lang_code="\([^"]*\)".*/\1/p'`
+         $getCommand $getArgs "$id.$tid.xml" "http://video.google.com/videotranscript?docid=$id&type=track&name=$name&lang=$lang"
+       done) && break
+      if [ $retry_time -gt 32 ]; then
+        echo "Too many errors on $id, giving up on this one."
+        echo "$id" >> $HOMEBASE/failed.list
+        break
+      fi
+      echo "Error while downloading. Will retry in $retry_time seconds."
+      sleep $retry_time
+      retry_time=$(( $retry_time * 2 ))
     done
-fi
+  fi
 }
 
 if [ -n "$1" ];then 
