predict-download-size: go faster
Checking the size of multiple (15 by default, adjust to tase) videos
in parallel helps a lot.

A 200-item list now takes around 1 minute. The main factor now seems
to be CPU load due to youtube-dl, rather than network latency.

diff --git a/predict-download-size b/predict-download-size
--- a/predict-download-size
+++ b/predict-download-size
@@ -3,8 +3,6 @@
 # Calculate the total expected download size of a set of videos,
 # reading IDs from stdin.
 #
-# Slow, but faster than downloading until you run out of disk space :-)
-#
 set -eu
 set -o pipefail
 DLSCRIPT=$(which youtube-dl)
@@ -18,27 +16,63 @@ echo_size() {
     echo "$1: $(( $2 / 1024 / 1024 ))M"
 }
 
-sumfile=$(mktemp)
-trap "rm $sumfile" 0
+slave_output_dir="${1:-}"
 
-echo 0 > sumfile
-error_count=0
-while read id; do
-    if echo $id | grep = > /dev/null
-    then
-        id=$(echo $id | cut -f2 -d"=")
+if [ -n "$slave_output_dir" ]; then
+    if ! [ -d "$slave_output_dir" ]; then
+        echo "Error: You should run this script with no arguments, feed it a video list on stdin." >&2
+        exit 1
     fi
+    # We're a slave process
+    shift
+    for id in "$@"; do
+        if echo $id | grep = > /dev/null
+        then
+            id=$(echo $id | cut -f2 -d"=")
+        fi
+        outputfile="$slave_output_dir/$id"
+        if [ -f "$outputfile" ]; then
+            echo "DUP: $id" >&2
+        else
+            url=$($DLSCRIPT -g http://video.google.com/videoplay?docid=$id)
+            content_length=$(curl --silent --location --head "$url" | sed -n 's/\r//; s/Content-Length: //p')
+            echo "$content_length" > "${outputfile}.tmp.$$"
+            mv "${outputfile}.tmp.$$" "$outputfile"
+            if [ -n "$content_length" ]; then
+                echo "OK:  $id" >&2
+            else
+                echo "ERR: $id" >&2
+            fi
+        fi
+    done
+else
+    # We are the master
+    # make a directory for our slaves to write into
+    sizedir=$(mktemp -d)
+    sumfile=$(mktemp)
+    echo 0 > sumfile
+    trap "rm -rvf $sizedir $sumfile" 0
+
+    # tune this for best performance
+    slave_count=15
     
-    url=$($DLSCRIPT -g http://video.google.com/videoplay?docid=$id)
-    content_length=$(curl --silent --location --head "$url" | sed -n 's/\r//; s/Content-Length: //p')
-    if [ -n "$content_length" ]; then
-        echo_size "$id" "$content_length"
-        echo "$content_length +" >> sumfile
-    else
-        echo "$id: Error"
-        error_count=$(( $error_count + 1 ))
-    fi
-done
-echo p >> sumfile
-echo_size "Total" "$(dc < sumfile)"
-echo "Errors: $error_count"
+    # read arguments from stdin, distribute them to slaves
+    xargs -P$slave_count -n5 "$0" $sizedir
+
+    # slaves are done, add it all up
+    error_count=0
+    for sizefile in $sizedir/*; do
+        id=$(basename $sizefile)
+        content_length=$(cat $sizefile)
+        if [ -n "$content_length" ]; then
+            echo_size "$id" "$content_length"
+            echo "$content_length +" >> sumfile
+        else
+            echo "$id: Error"
+            error_count=$(( $error_count + 1 ))
+        fi
+    done
+    echo p >> sumfile
+    echo_size "Total" "$(dc < sumfile)"
+    echo "Errors: $error_count"
+fi
